// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartDocumentPlatform.Api.Data;

#nullable disable

namespace SmartDocumentPlatform.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916152739_StableDocumentHistory")]
    partial class StableDocumentHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartDocumentPlatform.Api.Entities.DocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BlurDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("blur_detected");

                    b.Property<bool?>("DocumentDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("document_detected");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Orientation")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("orientation");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<string>("OriginalImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_image_path");

                    b.Property<string>("ProcessedImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("processed_image_path");

                    b.Property<long?>("ProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ms");

                    b.Property<double?>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<double?>("RotationDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("rotation_degrees");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("processing_status");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_documents_uploaded_at_id");

                    b.ToTable("documents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
